Fix oc command
konveyor/mig-ui pull request #1050
Opened 2020-10-29 19:53 UTC by ibolton336

Closes #1033

2020-10-29 21:59 UTC, eriknelson commented
@ibolton336 looks like this guy is failing the linter, trying to test in the meantime

2020-10-29 22:33 UTC, eriknelson commented
![image](https://user-images.githubusercontent.com/410933/97639568-37ef5800-1a15-11eb-980f-9f0178bfc111.png)

Saw this copying the backup

2020-10-29 22:34 UTC, eriknelson commented
![image](https://user-images.githubusercontent.com/410933/97639658-62411580-1a15-11eb-84d2-9b77426c4a0e.png)
And copying the Restore

2020-10-29 22:36 UTC, eriknelson requested changes
Small code q and linter updates

2020-10-29 22:36 UTC, eriknelson commented on src/app/home/pages/PlanDebugPage/components/TreeActionsDropdown.tsx
> +  (state) => {
Is this safe to remove if it's not returning anything?

2020-10-29 22:36 UTC, eriknelson commented
@vconzola Could you ack?

2020-10-29 23:52 UTC, vconzola commented
@ibolton336 Minor thing and can be done in a different PR if you need to merge this right away @eriknelson , but the "Run the oc command..." text should under the alert title as shown in the second example under Inline variations here: https://www.patternfly.org/v4/components/alert

2020-11-01 11:44 UTC, apinnick commented on src/app/home/pages/PlanDebugPage/components/TreeActionsDropdown.tsx
> +      `Copied to clipboard! Run the oc get command on
@eriknelson 
Suggested rewrite of error mesage: 
"Command copied to clipboard. Run 'oc get <resource>' on the ${clusterType} cluster to view resource details."

2020-11-01 11:45 UTC, apinnick commented on src/app/home/pages/PlanDebugPage/helpers.ts
> +        ocCommand: `Failed to copy command!`,
@eriknelson 
Suggest you change 'Failed to copy command!' to "Command was not copied."

2020-11-01 11:53 UTC, eriknelson requested changes
Suggested message changes

2020-11-10 02:18 UTC, eriknelson approved these changes

2020-11-10 02:18 UTC, merged